name: Arachnae Tests

on: push

jobs:
  js_test:
    name: Test components
    runs-on: ubuntu-latest

    strategy:
      matrix:
        react: ["16.14.0"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install Dependencies
        run: npm install
      - name: Install React
        run: npm install react@${{ matrix.react }} react-dom@${{ matrix.react }}
      - name: Type Check
        run: npm run flow
      - name: Format
        run: npm run prettier
      - name: Format
        run: npm run test

  report_coverage:
    name: Send Test Coverage to CodeClimate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install Dependencies
        run: npm install
      - name: Install React
        run: npm install react@16.14.0 react@16.14.0
      - name: Test Project
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run test
